[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "maestro-sdk"
version = "0.1.0"
description = "Python SDK client for Netflix Maestro workflow orchestrator"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Jun He", email = "jun-he@users.noreply.github.com"}
]
license = {text = "Apache-2.0"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Languange :: Python :: 3",
    "Programming Languange :: Python :: 3.10",
    "Programming Languange :: Python :: 3.11",
    "Programming Languange :: Python :: 3.12",
    "Programming Languange :: Python :: 3.13",
    "Typing :: Typed",
]
dependencies = [
    "pyyaml>=6.0",
]
keywords = ["maestro", "workflow", "orchestration", "SDK", "DSL"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "mypy>=1.0",
    "types-PyYAML>=6.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["maestro*"]

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
